[profile.default]
auto_detect_remappings = false
src = "contracts/src"
out = "out"
libs = ["lib"]
test = "contracts/test"
script = "contracts/script"
evm_version = 'cancun'

[rpc_endpoints]
mainnet = "https://ethereum-rpc.publicnode.com"
